### ISSUE TITLE
Index Error when scanning QR Code

### ISSUE THREAD

**Issue by sikaili99** [decentralised-dataexchange/PyDIVOC#1]
I am getting an error when I try to scan a qr code  sample provided [here](https://www.lfph.io/2021/10/13/divoc/) or anyother DIVOC qr code.

```
ivoc_covid19_qr
    qr_bytes = results[0].data
IndexError: list index out of range
```
If possible can you provide a sample QR for testing, it can be great. Thank

**Comment by georgepadayatti** [comment]
@Mathewsmusukuma The QR code provided by LFPH is invalid. To obtain a sample QR code, you can follow the steps provided here - https://divoc.digit.org/divoc-demo/citizen-portal
